In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt

# Change the plot size.
plt.rcParams['figure.figsize'] = [18.0, 12.0]

In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

In [4]:
# import my Finance Analysis Tools (fat)
import finance as fat

In [5]:
TICKER = 'IAU'
PATH = f'data/{TICKER}-test'
FILE = 'IAU-predictions-20180223-003722.csv'

In [9]:
data = fat.get_price_data(TICKER)

Loaded data for IAU: 2005-01-28 to 2018-02-21.

In [12]:
data['Next Day Open'] = data['Open'].shift(-1)
data['Next Day Adj Close'] = data['Adj Close'].shift(-1)
data['Next Day Gain'] = data['Next Day Adj Close'] - data['Next Day Open']
data['Next Day % Gain'] = 100 * data['Next Day Gain'] / data['Next Day Open']

In [14]:
data = data.sort_values('Next Day % Gain', ascending=False)

,Open,High,Low,Close,Adj Close,Volume,Next Day Open,Next Day Adj Close,Next Day Gain,Next Day % Gain
Date,,,,,,,,,,
2008-09-16,7.675000,7.735000,7.634000,7.659000,7.659000,5443000,7.717000,8.555000,0.838000,10.859142
2013-09-17,12.750000,12.770000,12.680000,12.720000,12.720000,2327800,12.600000,13.280000,0.680000,5.396825
2009-03-17,9.029000,9.064000,8.985000,9.016000,9.016000,3536000,8.880000,9.322000,0.442000,4.977477
2008-10-23,6.981000,7.222000,6.956000,7.105000,7.105000,8329000,6.923000,7.212000,0.289000,4.174491
2008-10-08,9.081000,9.085000,8.819000,8.975000,8.975000,15305000,8.742000,9.100000,0.358000,4.095173
2008-11-20,7.318000,7.424000,7.249000,7.376000,7.376000,6909000,7.604000,7.915000,0.311000,4.089953
2013-06-27,11.980000,12.000000,11.630000,11.650000,11.650000,10556900,11.570000,11.990000,0.420000,3.630078
2008-11-03,7.155000,7.220000,7.112000,7.125000,7.125000,2876000,7.319000,7.565000,0.246000,3.361115
2008-08-18,7.849000,7.919000,7.785000,7.899000,7.899000,4790000,7.797000,8.059000,0.262000,3.360267
2012-01-24,16.230000,16.290001,16.200001,16.240000,16.240000,3215700,16.160000,16.700001,0.540001,3.341590
2014-11-13,11.270000,11.310000,11.200000,11.240000,11.240000,2878900,11.160000,11.530000,0.370000,3.315412
2009-01-28,8.833000,8.843000,8.687000,8.737000,8.737000,11457000,8.672000,8.958000,0.286000,3.297970
2011-08-24,17.840000,17.879999,17.070000,17.209999,17.209999,45029800,16.740000,17.280001,0.540001,3.225812
2013-05-17,13.380000,13.410000,13.160000,13.170000,13.170000,11329600,13.150000,13.570000,0.420000,3.193916
2008-09-26,8.703000,9.003000,8.658000,8.693000,8.693000,6774000,8.697000,8.944000,0.247000,2.840060
2013-08-14,12.830000,12.980000,12.830000,12.970000,12.970000,4629400,12.880000,13.240000,0.360000,2.795031
2016-02-17,11.650000,11.720000,11.600000,11.640000,11.640000,11903100,11.630000,11.950000,0.320000,2.751505
2011-10-24,16.100000,16.180000,16.059999,16.139999,16.139999,3459300,16.170000,16.610001,0.440001,2.721095
2006-07-18,6.470000,6.470000,6.240000,6.286000,6.286000,2310000,6.250000,6.419000,0.169000,2.704000
2008-11-12,7.152000,7.190000,6.987000,7.034000,7.034000,3911000,7.050000,7.240000,0.190000,2.695035
2007-02-20,6.583000,6.647000,6.506000,6.537000,6.537000,1533000,6.563000,6.736000,0.173000,2.635990
2009-11-02,10.358000,10.430000,10.331000,10.395000,10.395000,2881000,10.381000,10.654000,0.273000,2.629804
2016-03-15,11.880000,11.910000,11.850000,11.910000,11.910000,5868300,11.850000,12.160000,0.310000,2.616034
2006-04-18,6.150000,6.200000,6.116000,6.200000,6.200000,1983000,6.215000,6.376000,0.161000,2.590507
2008-02-19,9.145000,9.203000,9.114000,9.169000,9.169000,1361000,9.106000,9.338000,0.232000,2.547771
2008-12-24,8.260000,8.363000,8.256000,8.350000,8.350000,1133000,8.358000,8.570000,0.212000,2.536492
2014-11-28,11.440000,11.470000,11.280000,11.290000,11.290000,10942400,11.460000,11.750000,0.290000,2.530541
2008-09-19,8.555000,8.648000,8.419000,8.626000,8.626000,9050000,8.704000,8.912000,0.208000,2.389706
2010-05-05,11.367000,11.532000,11.340000,11.517000,11.517000,3388000,11.577000,11.852000,0.275000,2.375399
2009-03-04,9.034000,9.042000,8.852000,8.907000,8.907000,8914000,8.996000,9.207000,0.211000,2.345487
...,...,...,...,...,...,...,...,...,...,...
2005-12-19,5.061000,5.078000,5.016000,5.027000,5.027000,1573000,5.038000,4.910000,-0.128000,-2.540691
2011-12-13,16.240000,16.370001,15.820000,15.900000,15.900000,13017200,15.720000,15.320000,-0.400000,-2.544529
2009-02-27,9.438000,9.458000,9.113000,9.266000,9.266000,11833000,9.348000,9.102000,-0.246000,-2.631579
2008-03-03,9.772000,9.783000,9.683000,9.740000,9.740000,6246000,9.738000,9.475000,-0.263000,-2.700760
2013-06-26,12.040000,12.050000,11.870000,11.890000,11.890000,11911600,11.980000,11.650000,-0.330000,-2.754591
2008-09-17,7.717000,8.566000,7.717000,8.555000,8.555000,13085000,8.564000,8.324000,-0.240000,-2.802429
2009-02-23,9.672000,9.822000,9.600000,9.775000,9.775000,28054000,9.756000,9.480000,-0.276000,-2.829028
2008-07-21,9.486000,9.531000,9.455000,9.531000,9.531000,1452000,9.583000,9.311000,-0.272000,-2.838360
2006-07-17,6.505000,6.536000,6.377000,6.403000,6.403000,2508000,6.470000,6.286000,-0.184000,-2.843895
2011-09-22,16.959999,17.070000,16.780001,16.969999,16.969999,17954700,16.490000,16.020000,-0.470000,-2.850212
2009-12-03,11.869000,11.958000,11.815000,11.883000,11.883000,4703000,11.724000,11.387000,-0.337000,-2.874446
2008-01-31,9.110000,9.177000,9.084000,9.150000,9.150000,3940000,9.196000,8.930000,-0.266000,-2.892562
2011-09-27,16.190001,16.270000,16.030001,16.110001,16.110001,15390700,16.120001,15.650000,-0.470001,-2.915639
2008-10-01,8.631000,8.797000,8.531000,8.625000,8.625000,4022000,8.464000,8.217000,-0.247000,-2.918242
2008-03-17,9.956000,10.048000,9.826000,9.939000,9.939000,11505000,9.964000,9.665000,-0.299000,-3.000803
2007-11-06,8.146000,8.165000,8.108000,8.141000,8.141000,5864000,8.500000,8.244000,-0.256000,-3.011765
2013-04-11,15.140000,15.250000,15.130000,15.180000,15.180000,5016400,14.930000,14.470000,-0.460000,-3.081045
2008-10-29,7.504000,7.633000,7.366000,7.429000,7.429000,4884000,7.491000,7.260000,-0.231000,-3.083700
2010-06-30,12.110000,12.220000,12.100000,12.170000,12.170000,2973500,12.100000,11.710000,-0.390000,-3.223140
2008-09-09,7.743000,7.779000,7.640000,7.640000,7.640000,3364000,7.689000,7.440000,-0.249000,-3.238393
2008-10-21,7.582000,7.691000,7.550000,7.628000,7.628000,5800000,7.445000,7.196000,-0.249000,-3.344527
2013-04-12,14.930000,14.960000,14.410000,14.470000,14.470000,30899600,13.670000,13.190000,-0.480000,-3.511339
2011-08-23,18.260000,18.420000,17.790001,17.809999,17.809999,20238900,17.840000,17.209999,-0.630001,-3.531396
2006-06-12,6.073000,6.095000,6.001000,6.008000,6.008000,1199000,5.805000,5.587000,-0.218000,-3.755383
2008-08-08,8.442000,8.471000,8.387000,8.434000,8.434000,4547000,8.449000,8.131000,-0.318000,-3.763759
2008-10-15,8.223000,8.444000,8.221000,8.358000,8.358000,9373000,8.254000,7.939000,-0.315000,-3.816331
2006-04-19,6.215000,6.398000,6.205000,6.376000,6.376000,2976000,6.351000,6.105000,-0.246000,-3.873406
2012-02-28,17.340000,17.459999,17.320000,17.410000,17.410000,4800100,17.370001,16.480000,-0.890001,-5.123782
2008-10-09,8.742000,9.100000,8.680000,9.100000,9.100000,14974000,8.952000,8.327000,-0.625000,-6.981680
2018-02-21,12.800000,12.830000,12.700000,12.710000,12.710000,13893600,NaN,NaN,NaN,NaN

In [19]:
big_gain = data.loc[data['Next Day % Gain'] > 1.0]
big_gain = big_gain.sort_index()
len(big_gain)

243

In [20]:
big_gain

,Open,High,Low,Close,Adj Close,Volume,Next Day Open,Next Day Adj Close,Next Day Gain,Next Day % Gain
Date,,,,,,,,,,
2005-04-18,4.258,4.280,4.258,4.273,4.273,183000,4.280,4.333,0.053,1.238318
2005-06-09,4.233,4.244,4.217,4.232,4.232,151000,4.227,4.270,0.043,1.017270
2005-08-10,4.354,4.366,4.349,4.362,4.362,408000,4.392,4.450,0.058,1.320583
2005-09-20,4.650,4.657,4.628,4.630,4.630,759000,4.663,4.710,0.047,1.007935
2005-09-23,4.614,4.629,4.599,4.628,4.628,486000,4.586,4.658,0.072,1.569996
2005-09-27,4.620,4.636,4.573,4.628,4.628,2277000,4.636,4.685,0.049,1.056946
2005-10-06,4.686,4.730,4.686,4.727,4.727,661000,4.704,4.752,0.048,1.020408
2005-11-15,4.684,4.689,4.662,4.664,4.664,320000,4.727,4.775,0.048,1.015443
2005-12-05,5.051,5.085,5.034,5.078,5.078,1324000,5.040,5.096,0.056,1.111111
2005-12-07,5.125,5.152,5.117,5.140,5.140,1114000,5.136,5.196,0.060,1.168224
2005-12-21,4.915,4.944,4.882,4.941,4.941,1878000,4.959,5.025,0.066,1.330913
2005-12-30,5.126,5.174,5.124,5.173,5.173,2655000,5.236,5.321,0.085,1.623377
2006-01-05,5.258,5.271,5.219,5.236,5.236,1446000,5.319,5.382,0.063,1.184433
2006-01-06,5.319,5.393,5.317,5.382,5.382,1969000,5.350,5.465,0.115,2.149533
2006-01-12,5.434,5.471,5.411,5.448,5.448,2158000,5.463,5.554,0.091,1.665751
2006-01-27,5.606,5.624,5.561,5.571,5.571,1682000,5.600,5.677,0.077,1.375000
2006-02-13,5.472,5.495,5.361,5.371,5.371,2014000,5.395,5.457,0.062,1.149212
2006-02-15,5.415,5.433,5.343,5.382,5.382,1990000,5.353,5.461,0.108,2.017560
2006-03-09,5.467,5.482,5.423,5.435,5.435,1151000,5.323,5.390,0.067,1.258689
2006-03-13,5.413,5.450,5.398,5.437,5.437,660000,5.430,5.498,0.068,1.252302
2006-03-28,5.665,5.666,5.601,5.614,5.614,3269000,5.646,5.717,0.071,1.257527
2006-04-12,5.955,5.980,5.930,5.952,5.952,881000,5.908,5.968,0.060,1.015572
2006-04-13,5.908,5.968,5.898,5.968,5.968,1070000,6.048,6.123,0.075,1.240079
2006-04-18,6.150,6.200,6.116,6.200,6.200,1983000,6.215,6.376,0.161,2.590507
2006-04-20,6.351,6.351,6.060,6.105,6.105,4284000,6.255,6.332,0.077,1.231015
2006-04-27,6.300,6.410,6.288,6.301,6.301,1403000,6.420,6.518,0.098,1.526480
2006-05-01,6.595,6.600,6.508,6.522,6.522,2640000,6.580,6.669,0.089,1.352584
2006-05-08,6.750,6.772,6.681,6.768,6.768,1961000,6.868,6.973,0.105,1.528829
2006-05-09,6.868,6.979,6.854,6.973,6.973,2624000,6.960,7.055,0.095,1.364943
2006-05-19,6.590,6.620,6.475,6.570,6.570,5614000,6.420,6.547,0.127,1.978193
...,...,...,...,...,...,...,...,...,...,...
2014-09-24,11.800,11.850,11.770,11.790,11.790,2539300,11.710,11.830,0.120,1.024765
2014-11-06,11.070,11.130,11.050,11.070,11.070,4455700,11.150,11.370,0.220,1.973094
2014-11-13,11.270,11.310,11.200,11.240,11.240,2878900,11.160,11.530,0.370,3.315412
2014-11-28,11.440,11.470,11.280,11.290,11.290,10942400,11.460,11.750,0.290,2.530541
2014-12-31,11.570,11.580,11.410,11.440,11.440,7066100,11.330,11.500,0.170,1.500441
2015-01-02,11.330,11.560,11.310,11.500,11.500,2221500,11.560,11.680,0.120,1.038062
2015-01-29,12.290,12.320,12.110,12.160,12.160,7300200,12.220,12.430,0.210,1.718494
2015-03-17,11.080,11.220,11.060,11.100,11.100,3226300,11.120,11.320,0.200,1.798561
2015-04-24,11.490,11.500,11.360,11.400,11.400,1577000,11.470,11.630,0.160,1.394943
2015-07-23,10.580,10.620,10.500,10.520,10.520,7157900,10.450,10.620,0.170,1.626794
2015-09-16,10.740,10.860,10.740,10.810,10.810,3535100,10.790,10.940,0.150,1.390176
2015-10-13,11.240,11.290,11.230,11.280,11.280,5965500,11.350,11.480,0.130,1.145374
2015-12-03,10.200,10.290,10.170,10.260,10.260,8719000,10.360,10.500,0.140,1.351351
2015-12-10,10.340,10.370,10.330,10.350,10.350,6456100,10.280,10.390,0.110,1.070039
2016-02-02,10.890,10.920,10.830,10.910,10.910,17392700,10.900,11.030,0.130,1.192661
2016-02-04,11.150,11.180,11.090,11.170,11.170,9719900,11.090,11.330,0.240,2.164112
2016-02-17,11.650,11.720,11.600,11.640,11.640,11903100,11.630,11.950,0.320,2.751505
2016-02-26,11.860,11.880,11.700,11.810,11.810,5144800,11.870,11.990,0.120,1.010952
2016-03-02,11.950,12.010,11.920,11.970,11.970,11521800,12.000,12.170,0.170,1.416667
2016-03-15,11.880,11.910,11.850,11.910,11.910,5868300,11.850,12.160,0.310,2.616034
2016-03-28,11.790,11.800,11.730,11.780,11.780,3602500,11.850,11.980,0.130,1.097046
2016-07-20,12.680,12.740,12.650,12.670,12.670,4200300,12.700,12.860,0.160,1.259843
2016-07-26,12.740,12.740,12.700,12.730,12.730,2071300,12.810,12.940,0.130,1.014832
2016-09-02,12.760,12.780,12.680,12.780,12.780,5092100,12.860,13.010,0.150,1.166407
2017-02-14,11.880,11.880,11.760,11.820,11.820,8850100,11.750,11.870,0.120,1.021277
2017-03-14,11.570,11.620,11.520,11.540,11.540,4593600,11.560,11.740,0.180,1.557093
2017-07-25,12.030,12.070,12.010,12.030,12.030,19924100,11.990,12.120,0.130,1.084237
2017-08-25,12.420,12.440,12.260,12.420,12.420,20144300,12.470,12.600,0.130,1.042502
2017-09-22,12.450,12.480,12.430,12.470,12.470,7291100,12.420,12.600,0.180,1.449275
2018-02-13,12.740,12.770,12.700,12.760,12.760,8174100,12.800,12.980,0.180,1.406250

In [240]:
predict = pd.read_csv(f'{PATH}/{FILE}')
predict = predict.set_index('Date')

In [241]:
predict.head()

,Month,Week,Day,Dayofweek,Dayofyear,Days since updated gold price usd,Is_month_end,Is_month_start,Is_quarter_end,Is_quarter_start,...,Volume SMA100,Volume SMA200,pct diff Volume SMA3,pct diff Volume SMA5,pct diff Volume SMA10,pct diff Volume SMA20,pct diff Volume SMA50,pct diff Volume SMA100,pct diff Volume SMA200,Will Close Higher Tomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2015-08-21,8,34,21,4,233,20.0,False,False,False,False,...,2549062.0,3641629.5,-15.692302,18.573483,42.078293,49.529427,41.621037,78.602950,25.018210,26.086124
2015-08-24,8,35,24,0,236,23.0,False,False,False,False,...,2604616.0,3638480.0,6.049517,48.946842,109.839340,132.049710,128.146760,192.999040,109.744180,48.456825
2015-08-25,8,35,25,1,237,24.0,False,False,False,False,...,2643510.0,3644522.5,-4.794828,-3.983591,43.462845,62.879505,65.800610,114.268150,55.416794,57.432760
2015-08-26,8,35,26,2,238,25.0,False,False,False,False,...,2644652.0,3642706.0,-46.942250,-52.561325,-25.427914,-18.604883,-17.126911,8.017993,-21.577530,143.165620
2015-08-27,8,35,27,3,239,26.0,False,False,False,False,...,2688441.0,3656939.5,18.409332,5.786842,32.002270,50.331715,58.115566,106.669960,51.935790,50.143867

In [242]:
data = data.join(predict['Will Close Higher Tomorrow'])

In [243]:
data = data.dropna()
data.head()

,Open,High,Low,Close,Adj Close,Volume,Next Day Adj Close,Next Day Gain,Will Close Higher Tomorrow
Date,,,,,,,,,
2015-08-21,11.18,11.23,11.11,11.20,11.20,4552700,11.14,-0.06,26.086124
2015-08-24,11.26,11.31,11.07,11.14,11.14,7631500,11.02,-0.12,48.456825
2015-08-25,11.09,11.10,10.96,11.02,11.02,5664200,10.87,-0.15,57.432760
2015-08-26,10.87,10.90,10.80,10.87,10.87,2856700,10.85,-0.02,143.165620
2015-08-27,10.83,10.90,10.80,10.85,10.85,5556200,10.95,0.10,50.143867

In [245]:
thresh100 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 100.0])
thresh100

,Open,High,Low,Close,Adj Close,Volume,Next Day Adj Close,Next Day Gain,Will Close Higher Tomorrow
Date,,,,,,,,,
2015-08-26,10.87,10.90,10.80,10.87,10.87,2856700,10.85,-0.02,143.165620
2015-12-17,10.18,10.19,10.12,10.15,10.15,10515000,10.29,0.14,102.566790
2015-12-31,10.24,10.27,10.22,10.23,10.23,5240700,10.38,0.15,108.538216
2016-02-22,11.65,11.73,11.64,11.65,11.65,4084700,11.84,0.19,116.741720
2016-03-24,11.78,11.81,11.74,11.75,11.75,26374100,11.78,0.03,104.844290
2016-06-16,12.65,12.69,12.34,12.36,12.36,14666900,12.52,0.16,122.531220
2016-08-24,12.81,12.82,12.75,12.77,12.77,4695300,12.75,-0.02,102.327415
2016-11-14,11.72,11.83,11.67,11.73,11.73,17358800,11.83,0.10,196.813980
2016-11-15,11.77,11.84,11.75,11.83,11.83,9865900,11.79,-0.04,143.487800
2016-11-16,11.84,11.85,11.77,11.79,11.79,9302700,11.74,-0.05,142.973650
2016-11-25,11.45,11.47,11.35,11.37,11.37,4656900,11.50,0.13,134.579220
2016-11-30,11.38,11.40,11.27,11.29,11.29,17109700,11.27,-0.02,161.158890
2016-12-15,10.89,10.91,10.81,10.86,10.86,15655100,10.91,0.05,131.246230
2017-02-17,11.95,11.97,11.89,11.89,11.89,5523200,11.90,0.01,129.037930
2017-03-03,11.83,11.90,11.77,11.88,11.88,7965500,11.80,-0.08,105.312020
2017-03-06,11.86,11.87,11.79,11.80,11.80,5145000,11.71,-0.09,123.070340
2017-04-24,12.21,12.29,12.20,12.29,12.29,5454400,12.16,-0.13,133.912140
2017-05-03,12.05,12.06,11.92,11.92,11.92,28859700,11.81,-0.11,107.660805
2017-05-04,11.80,11.86,11.79,11.81,11.81,7499200,11.82,0.01,120.567940
2017-05-05,11.81,11.84,11.79,11.82,11.82,4265900,11.80,-0.02,110.417320
2017-07-25,12.03,12.07,12.01,12.03,12.03,19924100,12.12,0.09,115.415760
2017-10-05,12.26,12.27,12.18,12.19,12.19,17760900,12.24,0.05,107.247410
2017-10-18,12.32,12.34,12.30,12.31,12.31,18808000,12.39,0.08,139.508710
2017-10-20,12.31,12.34,12.28,12.30,12.30,5942300,12.33,0.03,127.395840
2017-11-24,12.39,12.41,12.36,12.38,12.38,3483600,12.44,0.06,136.135350
2017-11-30,12.29,12.31,12.20,12.25,12.25,8158000,12.30,0.05,107.809425
2018-01-19,12.80,12.83,12.78,12.78,12.78,6918900,12.81,0.03,124.595060
2018-01-29,12.92,12.92,12.84,12.88,12.88,7974300,12.83,-0.05,155.419630

In [246]:
thresh100['Next Day Gain'].sum()

0.7300000000000022

In [252]:
thresh95 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 95.0])
thresh95

,Open,High,Low,Close,Adj Close,Volume,Next Day Adj Close,Next Day Gain,Will Close Higher Tomorrow
Date,,,,,,,,,
2015-08-26,10.87,10.90,10.80,10.87,10.87,2856700,10.85,-0.02,143.165620
2015-12-17,10.18,10.19,10.12,10.15,10.15,10515000,10.29,0.14,102.566790
2015-12-31,10.24,10.27,10.22,10.23,10.23,5240700,10.38,0.15,108.538216
2016-02-22,11.65,11.73,11.64,11.65,11.65,4084700,11.84,0.19,116.741720
2016-03-24,11.78,11.81,11.74,11.75,11.75,26374100,11.78,0.03,104.844290
2016-04-04,11.77,11.78,11.72,11.72,11.72,5664300,11.88,0.16,98.224625
2016-06-16,12.65,12.69,12.34,12.36,12.36,14666900,12.52,0.16,122.531220
2016-08-24,12.81,12.82,12.75,12.77,12.77,4695300,12.75,-0.02,102.327415
2016-11-14,11.72,11.83,11.67,11.73,11.73,17358800,11.83,0.10,196.813980
2016-11-15,11.77,11.84,11.75,11.83,11.83,9865900,11.79,-0.04,143.487800
2016-11-16,11.84,11.85,11.77,11.79,11.79,9302700,11.74,-0.05,142.973650
2016-11-18,11.66,11.70,11.61,11.63,11.63,8861400,11.68,0.05,95.432730
2016-11-25,11.45,11.47,11.35,11.37,11.37,4656900,11.50,0.13,134.579220
2016-11-30,11.38,11.40,11.27,11.29,11.29,17109700,11.27,-0.02,161.158890
2016-12-01,11.23,11.31,11.17,11.27,11.27,10729000,11.32,0.05,97.247440
2016-12-15,10.89,10.91,10.81,10.86,10.86,15655100,10.91,0.05,131.246230
2017-02-17,11.95,11.97,11.89,11.89,11.89,5523200,11.90,0.01,129.037930
2017-03-02,11.91,11.96,11.85,11.89,11.89,28204000,11.88,-0.01,97.552290
2017-03-03,11.83,11.90,11.77,11.88,11.88,7965500,11.80,-0.08,105.312020
2017-03-06,11.86,11.87,11.79,11.80,11.80,5145000,11.71,-0.09,123.070340
2017-04-24,12.21,12.29,12.20,12.29,12.29,5454400,12.16,-0.13,133.912140
2017-05-03,12.05,12.06,11.92,11.92,11.92,28859700,11.81,-0.11,107.660805
2017-05-04,11.80,11.86,11.79,11.81,11.81,7499200,11.82,0.01,120.567940
2017-05-05,11.81,11.84,11.79,11.82,11.82,4265900,11.80,-0.02,110.417320
2017-07-25,12.03,12.07,12.01,12.03,12.03,19924100,12.12,0.09,115.415760
2017-09-27,12.35,12.39,12.33,12.33,12.33,8721900,12.36,0.03,99.201454
2017-10-05,12.26,12.27,12.18,12.19,12.19,17760900,12.24,0.05,107.247410
2017-10-18,12.32,12.34,12.30,12.31,12.31,18808000,12.39,0.08,139.508710
2017-10-20,12.31,12.34,12.28,12.30,12.30,5942300,12.33,0.03,127.395840
2017-11-24,12.39,12.41,12.36,12.38,12.38,3483600,12.44,0.06,136.135350
2017-11-30,12.29,12.31,12.20,12.25,12.25,8158000,12.30,0.05,107.809425
2018-01-19,12.80,12.83,12.78,12.78,12.78,6918900,12.81,0.03,124.595060
2018-01-29,12.92,12.92,12.84,12.88,12.88,7974300,12.83,-0.05,155.419630

In [253]:
thresh95['Next Day Gain'].sum()

1.0100000000000016

In [247]:
thresh90 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 90.0])
thresh90

,Open,High,Low,Close,Adj Close,Volume,Next Day Adj Close,Next Day Gain,Will Close Higher Tomorrow
Date,,,,,,,,,
2015-08-26,10.87,10.90,10.80,10.87,10.87,2856700,10.85,-0.02,143.165620
2015-12-17,10.18,10.19,10.12,10.15,10.15,10515000,10.29,0.14,102.566790
2015-12-31,10.24,10.27,10.22,10.23,10.23,5240700,10.38,0.15,108.538216
2016-01-14,10.48,10.51,10.34,10.39,10.39,5323600,10.51,0.12,92.996185
2016-02-22,11.65,11.73,11.64,11.65,11.65,4084700,11.84,0.19,116.741720
2016-03-24,11.78,11.81,11.74,11.75,11.75,26374100,11.78,0.03,104.844290
2016-04-01,11.72,11.81,11.66,11.81,11.81,11475200,11.72,-0.09,91.605980
2016-04-04,11.77,11.78,11.72,11.72,11.72,5664300,11.88,0.16,98.224625
2016-05-26,11.87,11.87,11.75,11.76,11.76,4090400,11.68,-0.08,90.136110
2016-06-16,12.65,12.69,12.34,12.36,12.36,14666900,12.52,0.16,122.531220
2016-06-20,12.35,12.45,12.33,12.45,12.45,3983200,12.21,-0.24,92.745350
2016-08-24,12.81,12.82,12.75,12.77,12.77,4695300,12.75,-0.02,102.327415
2016-10-06,12.09,12.12,12.04,12.09,12.09,10992200,12.10,0.01,93.135170
2016-11-14,11.72,11.83,11.67,11.73,11.73,17358800,11.83,0.10,196.813980
2016-11-15,11.77,11.84,11.75,11.83,11.83,9865900,11.79,-0.04,143.487800
2016-11-16,11.84,11.85,11.77,11.79,11.79,9302700,11.74,-0.05,142.973650
2016-11-18,11.66,11.70,11.61,11.63,11.63,8861400,11.68,0.05,95.432730
2016-11-25,11.45,11.47,11.35,11.37,11.37,4656900,11.50,0.13,134.579220
2016-11-30,11.38,11.40,11.27,11.29,11.29,17109700,11.27,-0.02,161.158890
2016-12-01,11.23,11.31,11.17,11.27,11.27,10729000,11.32,0.05,97.247440
2016-12-15,10.89,10.91,10.81,10.86,10.86,15655100,10.91,0.05,131.246230
2017-02-17,11.95,11.97,11.89,11.89,11.89,5523200,11.90,0.01,129.037930
2017-03-02,11.91,11.96,11.85,11.89,11.89,28204000,11.88,-0.01,97.552290
2017-03-03,11.83,11.90,11.77,11.88,11.88,7965500,11.80,-0.08,105.312020
2017-03-06,11.86,11.87,11.79,11.80,11.80,5145000,11.71,-0.09,123.070340
2017-04-24,12.21,12.29,12.20,12.29,12.29,5454400,12.16,-0.13,133.912140
2017-05-03,12.05,12.06,11.92,11.92,11.92,28859700,11.81,-0.11,107.660805
2017-05-04,11.80,11.86,11.79,11.81,11.81,7499200,11.82,0.01,120.567940
2017-05-05,11.81,11.84,11.79,11.82,11.82,4265900,11.80,-0.02,110.417320
2017-07-25,12.03,12.07,12.01,12.03,12.03,19924100,12.12,0.09,115.415760
2017-09-27,12.35,12.39,12.33,12.33,12.33,8721900,12.36,0.03,99.201454
2017-10-05,12.26,12.27,12.18,12.19,12.19,17760900,12.24,0.05,107.247410
2017-10-18,12.32,12.34,12.30,12.31,12.31,18808000,12.39,0.08,139.508710
2017-10-20,12.31,12.34,12.28,12.30,12.30,5942300,12.33,0.03,127.395840
2017-10-26,12.26,12.26,12.16,12.18,12.18,9073900,12.23,0.05,92.487800
2017-10-31,12.22,12.23,12.19,12.21,12.21,6803700,12.25,0.04,94.730034
2017-11-24,12.39,12.41,12.36,12.38,12.38,3483600,12.44,0.06,136.135350
2017-11-30,12.29,12.31,12.20,12.25,12.25,8158000,12.30,0.05,107.809425
2018-01-19,12.80,12.83,12.78,12.78,12.78,6918900,12.81,0.03,124.595060
2018-01-29,12.92,12.92,12.84,12.88,12.88,7974300,12.83,-0.05,155.419630
2018-01-30,12.94,12.95,12.83,12.83,12.83,9532200,12.92,0.09,93.702995

In [248]:
thresh90['Next Day Gain'].sum()

0.9100000000000019

In [249]:
thresh80 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 80.0])
thresh80

,Open,High,Low,Close,Adj Close,Volume,Next Day Adj Close,Next Day Gain,Will Close Higher Tomorrow
Date,,,,,,,,,
2015-08-26,10.87,10.90,10.80,10.87,10.87,2856700,10.85,-0.02,143.165620
2015-11-05,10.69,10.71,10.65,10.65,10.65,5383600,10.50,-0.15,85.250244
2015-12-17,10.18,10.19,10.12,10.15,10.15,10515000,10.29,0.14,102.566790
2015-12-31,10.24,10.27,10.22,10.23,10.23,5240700,10.38,0.15,108.538216
2016-01-14,10.48,10.51,10.34,10.39,10.39,5323600,10.51,0.12,92.996185
2016-02-22,11.65,11.73,11.64,11.65,11.65,4084700,11.84,0.19,116.741720
2016-03-04,12.23,12.37,12.14,12.17,12.17,22198400,12.23,0.06,82.814060
2016-03-24,11.78,11.81,11.74,11.75,11.75,26374100,11.78,0.03,104.844290
2016-04-01,11.72,11.81,11.66,11.81,11.81,11475200,11.72,-0.09,91.605980
2016-04-04,11.77,11.78,11.72,11.72,11.72,5664300,11.88,0.16,98.224625
2016-05-20,12.12,12.15,12.04,12.06,12.06,4161100,12.05,-0.01,86.012660
2016-05-26,11.87,11.87,11.75,11.76,11.76,4090400,11.68,-0.08,90.136110
2016-06-16,12.65,12.69,12.34,12.36,12.36,14666900,12.52,0.16,122.531220
2016-06-20,12.35,12.45,12.33,12.45,12.45,3983200,12.21,-0.24,92.745350
2016-07-01,12.90,12.97,12.87,12.97,12.97,8911500,13.08,0.11,84.896385
2016-08-24,12.81,12.82,12.75,12.77,12.77,4695300,12.75,-0.02,102.327415
2016-08-25,12.72,12.76,12.72,12.75,12.75,3630700,12.73,-0.02,86.212425
2016-10-05,12.25,12.28,12.16,12.22,12.22,10179600,12.09,-0.13,87.786934
2016-10-06,12.09,12.12,12.04,12.09,12.09,10992200,12.10,0.01,93.135170
2016-10-24,12.26,12.26,12.14,12.18,12.18,2647700,12.27,0.09,84.440820
2016-11-01,12.41,12.45,12.38,12.39,12.39,9234700,12.48,0.09,85.542620
2016-11-14,11.72,11.83,11.67,11.73,11.73,17358800,11.83,0.10,196.813980
2016-11-15,11.77,11.84,11.75,11.83,11.83,9865900,11.79,-0.04,143.487800
2016-11-16,11.84,11.85,11.77,11.79,11.79,9302700,11.74,-0.05,142.973650
2016-11-18,11.66,11.70,11.61,11.63,11.63,8861400,11.68,0.05,95.432730
2016-11-23,11.50,11.51,11.38,11.43,11.43,16040500,11.37,-0.06,86.610460
2016-11-25,11.45,11.47,11.35,11.37,11.37,4656900,11.50,0.13,134.579220
2016-11-30,11.38,11.40,11.27,11.29,11.29,17109700,11.27,-0.02,161.158890
2016-12-01,11.23,11.31,11.17,11.27,11.27,10729000,11.32,0.05,97.247440
2016-12-15,10.89,10.91,10.81,10.86,10.86,15655100,10.91,0.05,131.246230
2017-01-26,11.45,11.47,11.40,11.44,11.44,9303600,11.46,0.02,87.749470
2017-02-17,11.95,11.97,11.89,11.89,11.89,5523200,11.90,0.01,129.037930
2017-03-02,11.91,11.96,11.85,11.89,11.89,28204000,11.88,-0.01,97.552290
2017-03-03,11.83,11.90,11.77,11.88,11.88,7965500,11.80,-0.08,105.312020
2017-03-06,11.86,11.87,11.79,11.80,11.80,5145000,11.71,-0.09,123.070340
2017-04-24,12.21,12.29,12.20,12.29,12.29,5454400,12.16,-0.13,133.912140
2017-05-03,12.05,12.06,11.92,11.92,11.92,28859700,11.81,-0.11,107.660805
2017-05-04,11.80,11.86,11.79,11.81,11.81,7499200,11.82,0.01,120.567940
2017-05-05,11.81,11.84,11.79,11.82,11.82,4265900,11.80,-0.02,110.417320
2017-06-15,12.06,12.09,12.04,12.07,12.07,4737200,12.07,0.00,81.589340
2017-06-30,11.94,11.98,11.93,11.94,11.94,5330700,11.73,-0.21,87.213030
2017-07-25,12.03,12.07,12.01,12.03,12.03,19924100,12.12,0.09,115.415760
2017-08-15,12.20,12.26,12.19,12.23,12.23,6404600,12.33,0.10,82.094010
2017-09-21,12.40,12.45,12.39,12.41,12.41,7243200,12.47,0.06,84.387245
2017-09-27,12.35,12.39,12.33,12.33,12.33,8721900,12.36,0.03,99.201454
2017-10-05,12.26,12.27,12.18,12.19,12.19,17760900,12.24,0.05,107.247410
2017-10-18,12.32,12.34,12.30,12.31,12.31,18808000,12.39,0.08,139.508710
2017-10-20,12.31,12.34,12.28,12.30,12.30,5942300,12.33,0.03,127.395840
2017-10-26,12.26,12.26,12.16,12.18,12.18,9073900,12.23,0.05,92.487800
2017-10-31,12.22,12.23,12.19,12.21,12.21,6803700,12.25,0.04,94.730034
2017-11-10,12.34,12.36,12.23,12.26,12.26,7736400,12.28,0.02,84.659050
2017-11-22,12.37,12.44,12.36,12.42,12.42,16405100,12.38,-0.04,81.237620
2017-11-24,12.39,12.41,12.36,12.38,12.38,3483600,12.44,0.06,136.135350
2017-11-30,12.29,12.31,12.20,12.25,12.25,8158000,12.30,0.05,107.809425
2018-01-19,12.80,12.83,12.78,12.78,12.78,6918900,12.81,0.03,124.595060
2018-01-29,12.92,12.92,12.84,12.88,12.88,7974300,12.83,-0.05,155.419630
2018-01-30,12.94,12.95,12.83,12.83,12.83,9532200,12.92,0.09,93.702995

In [251]:
thresh80['Next Day Gain'].sum()

0.8400000000000034

In [254]:
thresh70 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 70.0])
thresh70['Next Day Gain'].sum()

0.09000000000000696

In [255]:
thresh60 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 60.0])
thresh60['Next Day Gain'].sum()

7.105427357601002e-15

In [256]:
thresh50 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 50.0])
thresh50['Next Day Gain'].sum()

0.7800000000000029

In [257]:
thresh40 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 40.0])
thresh40['Next Day Gain'].sum()

-0.05999999999999872

In [258]:
thresh30 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 30.0])
thresh30['Next Day Gain'].sum()

0.909999999999993

In [259]:
thresh20 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 20.0])
thresh20['Next Day Gain'].sum()

0.5699999999999914

In [260]:
thresh10 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 10.0])
thresh10['Next Day Gain'].sum()

1.5099999999999998

In [262]:
thresh5 = pd.DataFrame(data.loc[data['Will Close Higher Tomorrow'] >= 5.0])
thresh5['Next Day Gain'].sum()

1.5600000000000005