# Nb-20180308-1457-BigGainPredict

Install and test TA-Lib:
Techncal analysis, python TA-Lib: https://github.com/mrjbq7/ta-lib

Looked into this, but decided not necessary at the moment. Fairly complex install

So,  get list of mega, large, and mid-cap companies on NYSE for looking for 1% price gain prediction using machine learning.

- https://www.nasdaq.com/screening/companies-by-industry.aspx?exchange=NYSE&marketcap=Mega-cap
- https://www.nasdaq.com/screening/companies-by-industry.aspx?exchange=NYSE&marketcap=Large-cap
- https://www.nasdaq.com/screening/companies-by-industry.aspx?exchange=NYSE&marketcap=Mid-cap

In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import datetime as dt
import numpy as np
import pandas as pd
import matplotlib.colors as colors
import matplotlib.dates as mdates
import matplotlib.ticker as mticker
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import matplotlib.font_manager as font_manager

In [3]:
import finance as fat

In [4]:
# Change the plot size.
plt.rcParams['figure.figsize'] = [18.0, 10.0]

In [17]:
c = pd.read_csv('data/NYSE-Companies-Mega-Large-Mid-Cap.csv')

In [18]:
c.head()

,Symbol,Name,LastSale,MarketCap,ADR TSO,IPOyear,Sector,Industry,Summary Quote,Unnamed: 9
0,BABA,Alibaba Group Holding Limited,187.18,4.802729e+11,NaN,2014.0,Miscellaneous,Business Services,https://www.nasdaq.com/symbol/baba,NaN
1,T,AT&T Inc.,37.11,2.279123e+11,NaN,NaN,Public Utilities,Telecommunications Equipment,https://www.nasdaq.com/symbol/t,NaN
2,BAC,Bank of America Corporation,32.20,3.298468e+11,NaN,NaN,Finance,Major Banks,https://www.nasdaq.com/symbol/bac,NaN
3,BA,Boeing Company (The),348.73,2.052242e+11,NaN,NaN,Capital Goods,Aerospace,https://www.nasdaq.com/symbol/ba,NaN
4,CVX,Chevron Corporation,113.35,2.165272e+11,NaN,NaN,Energy,Integrated oil Companies,https://www.nasdaq.com/symbol/cvx,NaN

In [19]:
c = c.sort_values('MarketCap',ascending=False)

In [20]:
c.head()

,Symbol,Name,LastSale,MarketCap,ADR TSO,IPOyear,Sector,Industry,Summary Quote,Unnamed: 9
0,BABA,Alibaba Group Holding Limited,187.18,4.802729e+11,NaN,2014.0,Miscellaneous,Business Services,https://www.nasdaq.com/symbol/baba,NaN
7,JPM,J P Morgan Chase & Co,114.74,3.937829e+11,NaN,NaN,Finance,Major Banks,https://www.nasdaq.com/symbol/jpm,NaN
8,JNJ,Johnson & Johnson,132.06,3.543040e+11,NaN,NaN,Health Care,Major Pharmaceuticals,https://www.nasdaq.com/symbol/jnj,NaN
2,BAC,Bank of America Corporation,32.20,3.298468e+11,NaN,NaN,Finance,Major Banks,https://www.nasdaq.com/symbol/bac,NaN
5,XOM,Exxon Mobil Corporation,74.12,3.140807e+11,NaN,NaN,Energy,Integrated oil Companies,https://www.nasdaq.com/symbol/xom,NaN

In [21]:
c.tail()

,Symbol,Name,LastSale,MarketCap,ADR TSO,IPOyear,Sector,Industry,Summary Quote,Unnamed: 9
981,NZF,Nuveen Municipal Credit Income Fund,14.19,2.016767e+09,NaN,2007.0,NaN,NaN,https://www.nasdaq.com/symbol/nzf,NaN
580,ARCO,Arcos Dorados Holdings Inc.,9.55,2.015742e+09,NaN,2011.0,Consumer Services,Restaurants,https://www.nasdaq.com/symbol/arco,NaN
734,DSL,DoubleLine Income Solutions Fund,19.84,2.010781e+09,NaN,2013.0,NaN,NaN,https://www.nasdaq.com/symbol/dsl,NaN
541,ADSW,"Advanced Disposal Services, Inc.",22.71,2.010027e+09,NaN,2016.0,Public Utilities,Environmental Services,https://www.nasdaq.com/symbol/adsw,NaN
781,SFUN,Fang Holdings Limited,4.52,2.002019e+09,NaN,2010.0,Technology,EDP Services,https://www.nasdaq.com/symbol/sfun,NaN

In [22]:
c = c[:5]

In [ ]:
for t in c['Symbol'] :
    d = fat.create_ml_ticker_features_df(t)